apiVersion: v1
kind: Pod
metadata:
  name: mongo-inspect
spec:
  restartPolicy: Never
  containers:
    - name: sh
      image: mongo:6.0
      command: ["bash","-lc","sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data/db
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: <PVC_NAME>
